language: node_js
node_js:
- 12
cache:
  yarn: true
  directories:
  - node_modules
env:
- CI=true
jobs:
  include:
  - stage: Tests
    name: ES Lint
    script: yarn test:lint:js
  - name: Unit Test Execution
    script: yarn test
  - stage: deployment
    name: Deploy artifacts to Heroku
deploy:
  provider: heroku
      app: ps-space
  api_key:
    secure: WbmqaV8M07O/s3y2sivcrPPHB8AakwroUphSIys6X5WhPmLEO1mR0D6ovw760swxSFtSQNlavXuSOyRBiQ79u1zqtZ0UZtvJxNSHnrdlWXSRxY5RmZadcUW3eHEjGYRf74BdmvoRoSmUPnd3qDE514zGmKGxywmPQC7JFMTtnzEb1OqgEobxmKpMKDHUlyPjvAdJxgL6luUEcxq3XKclhTK4QHWFC8DdSofnMqTz8Y0pyCiaLumBHq5Lv3EDLbGSe6I+rJWuKABrBRbxyLQws03GToC07TBM/vnBxuF2DwZuo6zgxQi8fg2Zn+XwMxRpmr2iN7+1sogW6/y0AMcvf+eXIGet9rWuUDpeRph6q+81RcNz+rwh9dzpQMO2e9NKuoZiMr6gJagonVjBvfaCc7tfBBce+6hE6wcHRnId37/rcZOBi2aA9hwknkXxCIALegQjAsxv1mkn0HaK9TaXjp3K73BdtMxyQvynso+gXOXihpHoJ/amLpd7Dm8zeFZTyFiBNBFdS4uOF/sNvPFqUU2fXU2VszmIyZqBjJuJxg/iAsmEvP0dYNZjh5BWm5gHggPrIzmuGZs5CU5syGNqbxGgSplQ9M8RWMlcBsZOdJhTnK3jF5g4v1JmYnEUYafW+kNraPTG3aoDksWTBGTCM5SJJOb8sMD0eXYyjLp9/5s=
